version: '3'

services:
  db:
    image: 'zcube/bitnami-compat-mongodb'
    ports:
      - 27017:27017
    restart: on-failure
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
      #- MONGO_INITDB_ROOT_USERNAME: root
      #- MONGO_INITDB_ROOT_PASSWORD: MongoDB
    volumes:
      - ./MongoDB:/data/db  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      #ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      #ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:27017/ 
    depends_on:
      - db    